{
 "title": "Apart cost app monitoring",
 "description": "designed to monitor and analyze the performance and operation of the application for calculating the cost of apartments",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total sum of all observed values for the histogram metric",
   "type": "timeseries",
   "description": "Total sum of all observed values for the histogram metric (Latency with only few buckets by handler. Made to be only used if aggregation by handler is important. )\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model response quantiles",
   "type": "timeseries",
   "description": "Median, 0.05 quantile and 0.95 quantile predicted value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent in seconds.",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Predictions chart",
   "type": "timeseries",
   "description": "Predictions chart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_sum[1m]) / increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident memory size in bytes.",
   "type": "gauge",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of requests to the service",
   "type": "timeseries",
   "description": "Count of events that have been observed for the histogram metric (Latency with only few buckets by handler. Made to be only used if aggregation by handler is important. )",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (rate of failed requests)",
   "type": "timeseries",
   "description": "Errors (rate of failed requests)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=\"error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}